// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdO-7yhC5ykYjr_d1gTVVm1ISw8S5jVfs',
    appId: '1:624738259232:web:eb243e599f4fe94b36c745',
    messagingSenderId: '624738259232',
    projectId: 'reapairoo',
    authDomain: 'reapairoo.firebaseapp.com',
    storageBucket: 'reapairoo.firebasestorage.app',
    measurementId: 'G-PEJEM0MRTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEHD4eAaC7aJ3JTBdLih1jP03Tx2k7qQA',
    appId: '1:624738259232:android:0a2ed2c41336efa836c745',
    messagingSenderId: '624738259232',
    projectId: 'reapairoo',
    storageBucket: 'reapairoo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUe-oHkpXBhDYpuLCVsRXPsIJx_pdxOPo',
    appId: '1:624738259232:ios:d00f3f32f6121a9b36c745',
    messagingSenderId: '624738259232',
    projectId: 'reapairoo',
    storageBucket: 'reapairoo.firebasestorage.app',
    iosBundleId: 'com.example.reapirooFirebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUe-oHkpXBhDYpuLCVsRXPsIJx_pdxOPo',
    appId: '1:624738259232:ios:bb544a03a200621c36c745',
    messagingSenderId: '624738259232',
    projectId: 'reapairoo',
    storageBucket: 'reapairoo.firebasestorage.app',
    iosBundleId: 'com.example.repairoo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdO-7yhC5ykYjr_d1gTVVm1ISw8S5jVfs',
    appId: '1:624738259232:web:9b29cfcd7a7863fd36c745',
    messagingSenderId: '624738259232',
    projectId: 'reapairoo',
    authDomain: 'reapairoo.firebaseapp.com',
    storageBucket: 'reapairoo.firebasestorage.app',
    measurementId: 'G-EZSNXJMP6Y',
  );
}